#!/bin/bash

METADATA=$(oc-metadata --cached)

metadata() {
  key=$1
  echo "$METADATA" | grep "^$key=" | cut -d= -f2 | sed "s/^['\"]//;s/['\"]$//"
}

cat<<EOF

*****************************************************************************
   To set up Camlistore, please run:
   $> camlistore-configure
   
   For further configuration, see https://camlistore.org/docs/server-config
   and edit /home/camli/.config/camlistore/server-config.json

   Then access your Camlistore instance at https://$(metadata PUBLIC_IP_ADDRESS):3179
*****************************************************************************
EOF
