#!/bin/bash

cat<<EOF

*****************************************************************************
   To set up Camlistore, please run:
   $> camlistore-configure -username desired_username -password desired_password
   
   For further configuration, see https://camlistore.org/docs/server-config
   and edit /home/camli/.config/camlistore/server-config.json

   Then access your Camlistore instance at https://$(oc-metadata --cached PUBLIC_IP_ADDRESS):3179/
*****************************************************************************
EOF
